name: jobmanager

services:
  jobmanager.rustfs:
    image: rustfs/rustfs:1.0.0-beta.8
    container_name: jobmanager.rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    hostname: rustfs
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_VOLUMES: /data
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
    volumes:
      - ./.tmp/rustfs_data:/data
  jobmanager.init:
    image: amazon/aws-cli:2.35.15
    container_name: jobmanager.init
    depends_on:
      - jobmanager.rustfs
    environment:
      - AWS_ACCESS_KEY_ID=rustfsadmin
      - AWS_SECRET_ACCESS_KEY=rustfsadmin
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until aws --endpoint-url http://rustfs:9000 s3 ls; do echo '...waiting for rustfs...' && sleep 1; done;
      aws --endpoint-url http://rustfs:9000 s3 mb s3://jobs || true;
      tail -f /dev/null
      "
